[
    {
        "name":"BondageBunny",
        "myCustomParameterThatIsEqualToOne":1
    },
    {
        "name":"KickStart",
        "hpDamageMultiplier":1.5
    },
    {
        "name":"Dummy"
    }
]